### ISSUE TITLE
Practica de Validación de Propuesta de Valor

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-cafe-huerto#2]
[Practica de Validacion de Propuesta de Valor_Edwin, Taolí, Alexis, Iván.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-cafe-huerto/files/6138415/Practica.de.Validacion.de.Propuesta.de.Valor_Edwin.Taoli.Alexis.Ivan.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
