### ISSUE TITLE
Practica de Costos

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-cafe-huerto#3]
[Practica de Costos_Edwin, Taolí, Iván, Alexis.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-cafe-huerto/files/6138430/Practica.de.Costos_Edwin.Taoli.Ivan.Alexis.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
